name: Build package

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build docker image
        run: docker build -t gentoo-build-package:latest .
      - name: Run docker container
        run: docker run gentoo-build-package:latest
