name: Build package

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Load packages from cache
        uses: actions/cache@v3
        with:
          path: packages
          key: packages
      - name: Build packages
        run: make build-image
      - name: Extract packages
        run: make run-image
        