name: build

on:
    pull_request:

jobs:
    build:
        runs-on: ubuntu:latest
        name: build packages
        steps:
            - name: say hello world
              run: echo hello world
            - name: checkout code
              uses: actions/checkout@v3
            - name: build image
              run: docker build -t gentoo/build .
            - name: run image
              run: docker run gentoo/build
