name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
            tags: gentoo-build-package:latest
      - uses: addnab/docker-run-action@v3
        with:
            image: gentoo-build-package
